"""update type

Revision ID: eed69473dc64
Revises: b2da2bb279a5
Create Date: 2021-11-22 10:27:49.251938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed69473dc64'
down_revision = 'b2da2bb279a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'fractal_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('fractal_index', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
