"""fix spelling

Revision ID: b2da2bb279a5
Revises: b81c52207a46
Create Date: 2021-11-22 10:15:44.602532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2da2bb279a5'
down_revision = 'b81c52207a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_constraint('candidates_comapany_id_fkey', 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'companies', ['company_id'], ['id'])
    op.drop_column('candidates', 'comapany_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('comapany_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key('candidates_comapany_id_fkey', 'candidates', 'companies', ['comapany_id'], ['id'])
    op.drop_column('candidates', 'company_id')
    # ### end Alembic commands ###
